# gcloud builds submit --config=cloudbuild.yaml .
steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: ['view.sh', '$PROJECT_ID', '${_SQL_FILE}']
timeout: 1200s
substitutions:
  _SQL_FILE: none
options:
    substitution_option: 'ALLOW_LOOSE'